version: "3.8"
services:
  nsqlookupd:
    image: nsqio/nsq:latest
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - nsq-network

  nsqd:
    image: nsqio/nsq:latest
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --broadcast-address=nsqd         # <-- sửa từ localhost thành nsqd
      --http-address=0.0.0.0:4151
      --tcp-address=0.0.0.0:4150
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    networks:
      - nsq-network

  nsqadmin:
    image: nsqio/nsq:latest
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
      - nsqd
    ports:
      - "4171:4171"
    networks:
      - nsq-network

networks:
  nsq-network:
    driver: bridge
